stages:
  - build
  - deploy

image:
  name: pandoc/latex:latest
  entrypoint: [""]

build:
  stage: build
  needs: []
  script:
    - ./create_pdf.sh
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  needs: []
  script:
    - ./create_html.sh
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
